version: '3.8'

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: tvtrader
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - ./pgdata:/pgdata
    ports:
      - '5432:5432'

  api:
    image: vhostpg
    depends_on:
      - db
    ports:
      - '4000:4000'
